version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Build phase - nothing to compile for plain Node.js app"
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
